name: jksb

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Cherkout
      uses: actions/checkout@v2

    - name: Install firefox and packages
      run: pip install -r requirements.txt

    - name: jksb
      env:
        NETID: ${{secrets.NETID}}
        PASSWORD: ${{secrets.PASSWORD}}
        RECURL: ${{secrets.RECURL}}
        TG_BOT_TOKEN: ${{secrets.TG_BOT_TOKEN}}
        TG_CHATID: ${{secrets.TG_CHATID}}
      run: python jksb_sysu.py
